<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliography [ 
<!ELEMENT index (#PCDATA | topic | person)*>
<!ELEMENT biblio (#PCDATA)>
<!ATTLIST biblio key CDATA #IMPLIED>
<!ELEMENT translator (#PCDATA)>
<!ELEMENT bibliography (#PCDATA | bibl)*>
<!ELEMENT authorstmt (#PCDATA | editor | author | a)*>
<!ELEMENT title (#PCDATA | title | compilor | author | biblio | i | ref | editor | sup)*>
<!ATTLIST title level CDATA #IMPLIED>
<!ELEMENT topic (#PCDATA | i | ref)*>
<!ELEMENT vols (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT person (#PCDATA)>
<!ELEMENT bibl (#PCDATA | authorstmt | titlestmt | pubstmt | index | ref)*>
<!ATTLIST bibl xml:id ID #IMPLIED>
<!ELEMENT titlestmt (#PCDATA | title | vols | eds | pubstmt | index | editor | translator | biblio)*>
<!ELEMENT pubstmt (#PCDATA | biblio | title | editor | titlestmt | pubstmt | index | ref | author | i | a)*>
<!ATTLIST pubstmt date CDATA #IMPLIED>
<!ELEMENT editor (#PCDATA | last | first | prefix | suffix)*>
<!ELEMENT i (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref n CDATA #IMPLIED>
<!ATTLIST ref type CDATA #IMPLIED>
<!ATTLIST ref xml:tartet CDATA #IMPLIED>
<!ATTLIST ref xml:taqrget CDATA #IMPLIED>
<!ATTLIST ref xml:target CDATA #IMPLIED>
<!ELEMENT compilor (#PCDATA)>
<!ELEMENT a (#PCDATA | last | first)*>
<!ATTLIST a href CDATA #IMPLIED>
<!ELEMENT suffix (#PCDATA)>
<!ELEMENT seg (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT eds (#PCDATA | editor | seg)*>
<!ELEMENT author (#PCDATA | last | first | suffix | prefix)*>
]>
<bibliography>
    <bibl xml:id="Gollanz1892">
        <authorstmt>
            <editor>
                <last>Gollanz</last>
                <first>Israel</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="a">Three Chansons of Hoccleve.</title>
            <title level="j">The Academy</title>
        </titlestmt>
        <pubstmt date="1892">41 (1892): 542</pubstmt>
        <index>
            <topic>Roundels</topic>
            <person>Hoccleve</person>
        </index>
    </bibl>
    <bibl xml:id="Acker1986">
        <authorstmt>
            <author>
                <last>Acker</last>
                <first>Paul</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">Harvard MS 1032: Exemplary Verse Concerning Charlemagne and
                Theobald.</title>
            <title level="j">Neuphilologische Mitteilungen</title>
        </titlestmt>
        <pubstmt date="1986">87 (1986): 354-64</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Acker1999">
        <authorstmt>
            <author>
                <last>Acker</last>
                <first>Paul</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">An Unedited Middle English Religious Lyric (IMEVS 250.3) in Plimpton MS
                Add. 2.</title>
            <title level="j">Notes and Queries</title>
        </titlestmt>
        <pubstmt date="1999">n. s. 46 (1999): 12</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ackerman1947">
        <authorstmt>
            <editor>
                <last>Ackerman</last>
                <first>Robert W.</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">Syre Gawaine and the Carle of Carlyle.</title>
            <title level="s">University of Michigan Contributions in Modern Philology</title>
        </titlestmt>
        <pubstmt date="1947">8 Ann Arbor, MI: University of Michigan Press, 1947</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Adam1887">
        <authorstmt>
            <editor>
                <last>Adam</last>
                <first>E.</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">Torrent of Portyngale</title>
            <title level="s">EETS</title>
        </titlestmt>
        <pubstmt date="1887">e.s. 51 (1887), repr. 1973</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Adams1924">
        <authorstmt>
            <author>
                <last>Adams</last>
                <first>Joseph Quincy</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Chief Pre-Shakespearean Dramas.</title>
        </titlestmt>
        <pubstmt date="1924">Boston: Houghton Mifflin, 1924</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Addington1845">
        <authorstmt>
            <author>
                <last>Addington</last>
                <first>Henry</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Some Account of the Abbey Church of St. Peter and St. Paul, at
                Dorchester, Oxfordshire.</title>
        </titlestmt>
        <pubstmt date="1845">Oxford: CK, 1845</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Adler1887">
        <authorstmt>
            <author>
                <last>Adler</last>
                <first>Guido</first>
            </author>
            <author><first>M.</first>
                <last>Kaluza</last>.</author>
        </authorstmt>
        <titlestmt>
            <title level="a">&#252;ber die Richard Rolle de Hampole zugeschriebene Paraphrase der
                sieben Busspsalmen.</title>
            <title level="j">Englische Studien</title>
        </titlestmt>
        <pubstmt date="1887">10 (1887): 215-55</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Adler1904">
        <authorstmt>
            <author>
                <last>Adler</last>
                <first>Guido</first>
            </author>
            <author><first>Oswald</first>
                <last>Koller</last>.</author>
        </authorstmt>
        <titlestmt>
            <title level="m">Secchs trienter Codices geistliche un weltliche Kompositionen des
                XV.Jhs. II. Auswahl. Denkm&#228;ler der Tonkunst in Osterreich</title>
        </titlestmt>
        <pubstmt date="1904">11 (1) (1904)</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Albrecht1954a">
        <authorstmt>
            <author>
                <last>Albrecht</last>
                <first>William Price</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a"><title level="m">The Loathly Lady</title> in Thomas of Erceldoune with
                a text of the poem printed in 1652.</title>
            <title level="j">Language and Literature</title>
        </titlestmt>
        <pubstmt date="1954">11. Albuquerque, New Mexico: University of New Mexico, 1954</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Albrecht1954b">
        <authorstmt>
            <author>
                <last>Albrecht</last>
                <first>William Price</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">A Seventeenth-century Text of Thomas of Erceldoune.</title>
            <title level="m">Medium &#198;vum</title>
        </titlestmt>
        <pubstmt date="1954">23 (1954): 88-95</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl>
        <authorstmt/>
        <titlestmt/>
        <pubstmt> Aldine Chaucer see <biblio key="Nicolas1866"/></pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Alexander1987">
        <authorstmt>
            <editor>
                <last>Alexander</last>
                <first>Jonathan</first>
            </editor>
            <editor>
                <first>Paul</first>
                <last>Binski</last>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">The Age of Chivalry: Art in Plantagenet England, 1200-1400.</title>
        </titlestmt>
        <pubstmt date="1987">London: Royal Academy of Arts in assoc. with Weidenfeld &#38; Nicolson,
            1987</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Allen1596">
        <authorstmt>
            <author>
                <last>Allen</last>
                <first>Robert</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">An Alphabet of the Holy Proverbs of King Solomon (STC 362).</title>
        </titlestmt>
        <pubstmt date="1596">London: R. Robinson for R. Dexter, 1596</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Allen1927">
        <authorstmt>
            <author>
                <last>Allen</last>
                <first>Hope Emily</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Writings Attributed to Richard Rolle.</title>
        </titlestmt>
        <pubstmt date="1927">New York: Modern Language Association of America, 1927</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Allen1931">
        <authorstmt>
            <author>
                <last>Allen</last>
                <first>Hope Emily</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">English Writings of Richard Rolle.</title>
        </titlestmt>
        <pubstmt date="1931">Oxford: Clarendon, 1931</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="AllenR1984">
        <authorstmt>
            <editor>
                <last>Allen</last>
                <first>Rosamund</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">King Horn: An Edition Based on Cambridge University Library MS Gg
                4.27.</title>
        </titlestmt>
        <pubstmt date="1984">New York: Garland, 1984</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Amassian1970">
        <authorstmt>
            <author>
                <last>Amassian</last>
                <first>Margaret</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">A Verse Life of John of Bridlington.</title>
            <title level="j">Neuphilologische Mitteilungen</title>
        </titlestmt>
        <pubstmt date="1970">71 (1970): 136-45</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Amherst1888">
        <authorstmt>
            <author>
                <last>Tyssen-Amherst</last>
                <first>Alicia M</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">On a Fifteenth Century Treatise on Gardening by &#8216;Mayster&#8217;
                John Gardener.</title>
            <title level="j">Archaeologia</title>
        </titlestmt>
        <pubstmt date="1888">54 (1888): 157-72</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Amours1892-97">
        <authorstmt>
            <editor>
                <last>Amours</last>
                <first>Fran&#231;ois Joseph</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">Scottish Alliterative Poems in Riming Stanzas.</title>
            <vols> 2 vols. </vols>
            <title level="s">Scottish Text Society</title>
        </titlestmt>
        <pubstmt date="1892">27 (1892), 38 (1897); Edinburgh, London: Blackwood, 1892-1897</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Amours1903-14">
        <authorstmt>
            <author>
                <last>Amours</last>
                <first>Fran&#231;ois Joseph</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Original Chronicle of Andrew of Wyntoun.</title>
            <vols> 6 vols. </vols>
            <title level="s">Scottish Text Society.</title>
        </titlestmt>
        <pubstmt date="1903-14">50, 53-4, 56-7, 63 Edinburgh, London: Blackwood, 1903-14</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ancestor1902">
        <authorstmt/>
        <titlestmt>
            <title level="a">A Fifteenth-Century Book of Arms.</title>
            <title level="j">The Ancestor</title>
        </titlestmt>
        <pubstmt date="1902">no. 3 (October, 1902): 185-213</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Anderson1663">
        <authorstmt>
            <author>
                <last>Anderson</last>
                <first>A.</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Testament of Cresseid Compyled by Master Robert Henrison.</title>
        </titlestmt>
        <pubstmt date="1663">Glasgow, 1663</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Anderson1793">
        <authorstmt>
            <author>
                <last>Anderson</last>
                <first>Robert</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Works of the British Poets, or, Complete Edition of the Poets of
                Great Britain.</title>
        </titlestmt>
        <pubstmt date="1793">13 vols. Vol. 1. Edinburgh, 1793; London, 1795</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Andrew1978">
        <authorstmt>
            <editor>
                <last>Andrew</last>
                <first>Malcolm</first>
            </editor>
            <editor>
                <first>Ronald</first>
                <last>Waldron</last>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">The Poems of the Pearl Manuscript: Pearl, Cleanness, Patience, Sir
                Gawain and the Green Knight.</title>
        </titlestmt>
        <pubstmt date="1978">London: Edward Arnold, and Berkeley: University of California, 1978;
            repr. York Medieval Texts, second series</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="AnnualReg1776">
        <authorstmt/>
        <titlestmt>
            <title level="m">The Annual Register, or a View of the History of Politics and
                Literature for the Year 1776.</title>
        </titlestmt>
        <pubstmt date="1777">London: Printed for J. Dodsley, in Pall-Mall, 1777</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Apponyi1903">
        <authorstmt>
            <author>
                <last>Apponyi</last>
                <first>S&#225;ndor</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Hungarica: Ungarn betreffende im Auslande gedruckte B&#252;cher und
                Flugschriften, gesammelt und beschrieben von Graf Alexander Apponyi.</title>
        </titlestmt>
        <pubstmt date="1903-27">4 vols. Munich: J. Rosenthal, 1903-27</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arber1882">
        <authorstmt>
            <author>
                <last>Arber</last>
                <first>Edward</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">An English Garner: Ingatherings from our history and
                literature.</title>
        </titlestmt>
        <pubstmt date="1882">London, 1882</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arber1895">
        <authorstmt>
            <author>
                <last>Arber</last>
                <first>Edward</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Revelation to the Monk of Evesham.</title>
        </titlestmt>
        <pubstmt date="1895">Westminster: A. Constable, 1895</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arber1900">
        <authorstmt>
            <author>
                <last>Arber</last>
                <first>Edward</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Surrey and Wyatt Anthology, 1509-1547 A.D.</title>
        </titlestmt>
        <pubstmt date="1900">London, New York: Frowde, 1900</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arber1901">
        <authorstmt>
            <author>
                <last>Arber</last>
                <first>Edward</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Dunbar Anthology, 1401-1508.</title>
        </titlestmt>
        <pubstmt date="1901">London, New York: Frowde, 1901</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="dArdenne1936">
        <authorstmt>
            <editor>
                <last>D&#8217;Ardenne</last>
                <first>S. R. T. O.</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">An edition of &#254;e Liflade ant te Passiun of Seinte Iuliene.</title>
            <title level="s">Bibl. de la Fac. de Philos. et Lettres de l&#8217;Univ. de
                Li&#233;ge</title>
        </titlestmt>
        <pubstmt date="1936">64 (1936); re-issued as <title level="s">EETS o.s. 248</title> (1961),
            repr. 1990</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arn1994">
        <authorstmt>
            <editor><last>Arn</last>,<first> Mary-Jo</first></editor>
        </authorstmt>
        <titlestmt>
            <title level="m">Fortunes Stabilnes: Charles of Orleans&#8217;s English Book of Love. A
                Critical Edition.</title>
        </titlestmt>
        <pubstmt date="1994">Binghamton, NY: Medieval and Renaissance Texts and Studies,
            1994</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arngart1955">
        <authorstmt>
            <author>
                <last>Arngart</last>
                <first>Olof Sigrid</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Proverbs of Alfred: an emended text.</title>
        </titlestmt>
        <pubstmt date="1955">Lund: Liber Laromedel/Gleerup, 1955</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arngart1973">
        <authorstmt>
            <author>
                <last>Arngart</last>
                <first>Olof Sigrid</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Two English Border Ballads: The Battle of Otterburn, Hunting of the
                Cheviot.</title>
            <title level="s">Acta Universitatis Lundensis, Sectio 1, Theologica, juridica,
                humaniora</title>
        </titlestmt>
        <pubstmt date="1973">18. Lund: Gleerup, 1973</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arngart1991">
        <authorstmt>
            <author>
                <last>Arngart</last>
                <first>Olof Sigrid</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">The Hunting of the Cheviot Ballad.</title>
            <title level="j">English Studies</title>
        </titlestmt>
        <pubstmt date="1991">72 (1991): 401-13 [a reconstructed text]</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arnold1882-85">
        <authorstmt>
            <editor>
                <last>Arnold</last>
                <first>Thomas</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">Symeonis Monachi Opera Omnia.</title>
            <title level="s">Rolls Series</title>
        </titlestmt>
        <pubstmt date="1882-85">75 2 vols. (1882-85; repr. Kraus, 1965)</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arnold1890-96">
        <authorstmt>
            <editor>
                <last>Arnold</last>
                <first>Thomas</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">Memorials of St. Edmund&#8217;s Abbey.</title>
            <vols> 3 vols. </vols>
            <title level="s">Rolls Series</title>
        </titlestmt>
        <pubstmt date="1890-96">96 (1890-96); repr. Kraus, 1965)</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Arthur1900-01">
        <authorstmt>
            <author>
                <last>Arthur</last>
                <first>H.</first>
                <suffix>viscount Dillon</suffix>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">On a Manuscript Collection of Ordinances of Chivalry.</title>
            <title level="j">Archaeologia</title>
        </titlestmt>
        <pubstmt date="1900-1">57 (1900-01): 29-70</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ashbee1902">
        <authorstmt>
            <author>
                <last>Ashbee</last>
                <first>Charles Robert</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Flower and the Leaf.</title>
        </titlestmt>
        <pubstmt date="1902">London: Essex House, 1902</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ashe2003">
        <authorstmt>
            <author>
                <last>Ashe</last>
                <first>Laura</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">The &#8216;Short Charter of Christ&#8217;: An Unpublished Longer
                Version, from Cambridge University Library MS Add. 6686.</title>
            <title level="j">Medium Aevum</title>
        </titlestmt>
        <pubstmt date="2003">72 (2003): 32-44</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ashburnham1849">
        <authorstmt>
            <author>
                <last>Ashburnham</last>
                <first>Bertram</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Catalogue of the Manuscripts at Ashburnham Place.</title>
            <vols> 2 vols. plus Appendix volume. </vols>
        </titlestmt>
        <pubstmt date="[1849]-1864">London: C. F. Hodgson, [1849]-1864</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ashmole1652">
        <authorstmt>
            <author>
                <last>Ashmole</last>
                <first>Elias</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Theatrum Chemicum Britannicum.</title>
        </titlestmt>
        <pubstmt date="1652">London: J. Grimond, 1652</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ashmole1672">
        <authorstmt>
            <author>
                <last>Ashmole</last>
                <first>Elias</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Institution, Laws &#38; Ceremonies of the Most Noble Order of the
                Garter.</title>
        </titlestmt>
        <pubstmt date="1672">London: 1672</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ashmole1719">
        <authorstmt>
            <author>
                <last>Ashmole</last>
                <first>Elias</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">The Antiquities of Berkshire.</title>
        </titlestmt>
        <pubstmt date="1719">3 vols. London: E. Curll, 1719</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ashton1882">
        <authorstmt>
            <editor>
                <first>John</first>
                <last>Ashton</last>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">A Ballade of the Scottysshe Kyng</title>
        </titlestmt>
        <pubstmt date="1882">London: Elliot Stock, 1882</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ashton1887">
        <authorstmt>
            <editor>
                <last>Ashton</last>
                <first>John</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">A Century of Ballads.</title>
        </titlestmt>
        <pubstmt date="1887">London, Elliot Stock, 1887</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Aspin1953">
        <authorstmt>
            <author>
                <last>Aspin</last>
                <first>Isabel Stewart Tod</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Anglo-Norman Political Songs.</title>
        </titlestmt>
        <pubstmt date="1953">Oxford: Clarendon, 1953</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Astle1775">
        <authorstmt>
            <author>
                <last>Astle</last>
                <first>Thomas</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="a">An Ancient Poem,</title>
            <title level="m">The Antiquarian Repertory.</title>
            <eds>
                <editor>
                    <first>Thomas</first>
                    <last>Astle</last>
                </editor>
                <editor>
                    <first>Francis</first>
                    <last>Grose</last>
                </editor>
            </eds>
        </titlestmt>
        <pubstmt date="1775">4 vols. London: Blyth, Sewell, Evans, 1775</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Atkins1922">
        <authorstmt>
            <editor>
                <last>Atkins</last>
                <first>John William Hey</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">The Owl and Nightingale.</title>
        </titlestmt>
        <pubstmt date="1922">Cambridge: UP, 1922</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Auden1938">
        <authorstmt>
            <editor>
                <last>Auden</last>
                <first>Wystan Hugh</first>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">The Oxford Book of Light Verse.</title>
        </titlestmt>
        <pubstmt date="1938">Oxford: Clarendon, 1938</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Auden1950">
        <authorstmt>
            <editor>
                <last>Auden</last>
                <first>Wystan Hugh</first>
            </editor>
            <editor>
                <first>Norman Holmes</first>
                <last>Pearson</last>
            </editor>
        </authorstmt>
        <titlestmt>
            <title level="m">Poets of the English Language.</title>
            <title level="s">Viking Portable Library</title>
        </titlestmt>
        <pubstmt date="1950">vol. 1. New York, 1950</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Ault1949">
        <authorstmt>
            <author>
                <last>Ault</last>
                <first>Norman</first>
            </author>
        </authorstmt>
        <titlestmt>
            <title level="m">Elizabethan Lyrics from the Original Texts.</title>
        </titlestmt>
        <pubstmt date="1949">3rd ed. New York: W. Sloane, 1949</pubstmt>
        <index>
            <topic/>
            <person/>
        </index>
    </bibl>
    <bibl xml:id="Aurner1926">
        <authorstmt>
            <author>
                <last>Aurner</last>
                <first>Nellie Slayton</first>
            </author>
        </authorstmt>
        <titlestmt>