<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glossary [
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref type CDATA #IMPLIED>
<!ATTLIST ref n CDATA #IMPLIED>
<!ELEMENT lemma (#PCDATA)>
<!ELEMENT glossary (#PCDATA | item)*>
<!ELEMENT def (#PCDATA | i | sup)*>
<!ELEMENT source (#PCDATA | ref | lemma | biblio | i | sup)*>
<!ELEMENT biblio (#PCDATA | key)*>
<!ATTLIST biblio key CDATA #IMPLIED>
<!ELEMENT item (#PCDATA | lemma | source | partOfSpeech | def)*>
<!ATTLIST item xml:id ID #IMPLIED>
<!ELEMENT i (#PCDATA)>
<!ELEMENT partOfSpeech (#PCDATA | i | sup)*>
<!ELEMENT sup (#PCDATA)>
]>

<glossary>
    <item xml:id="adawe">
        <lemma>adawe</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adverb</i></partOfSpeech>
        <def> Out of existence. Only in <i>to do</i> (also <i>bring</i>) (a person) <i>adawe</i>: to
            put (a person) to death; to do away with, kill</def>
    </item>
    <item xml:id="afald">
        <lemma>afald</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i> (1) </partOfSpeech>
        <def> Single, singular, sole, only. <i>Obs</i>.</def>
    </item>
    <item xml:id="afte">
        <lemma>afte</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>adverb</i>
        </partOfSpeech>
        <def> Back; wenden on ~, pervert</def>
    </item>
    <item xml:id="aknow">
        <source>
            <lemma>aknow</lemma>
            <ref type="url" n="http://www.dsl.ac.uk/">Dictionary of the Scots Language</ref>
        </source>
        <partOfSpeech><i>verb</i> (1.)</partOfSpeech>
        <def><i>Obs</i>. (<i>Eng. regional</i> (<i>north</i>.) in later use). <i>trans</i>. To know,
            recognize; to come to know, understand.</def>
    </item>
    <item xml:id="aland">
        <source>
            <lemma>aland</lemma>
            <ref type="url" n="http://www.dsl.ac.uk/">Dictionary of the Scots Language</ref>
        </source>
        <partOfSpeech><i>noun</i> (1.)</partOfSpeech>
        <def>A draught-horse, a cart-horse: an old horse or one of little value</def>
    </item>
    <item xml:id="aport">
        <lemma>aport</lemma>
        <source>
            <ref type="url" n="http://www.dsl.ac.uk/">Dictionary of the Scots Language</ref>
        </source>
        <partOfSpeech><i>noun</i></partOfSpeech>
        <def> Bearing, demeanour</def>
    </item>
    <item xml:id="an-inne">
        <lemma>an-inne</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>preposition</i></partOfSpeech>
        <def> Within</def>
    </item>
    <item xml:id="appeal">
        <lemma>appeal</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i> (1c) </partOfSpeech>
        <def> To accuse of a heinous crime whereby the accuser has received personal injury or
            wrong, for which he demands reparation</def>
    </item>
    <item xml:id="avale">
        <lemma>avale</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def>
            <i>intr</i>. Of persons: To defend; to come, go, or get down; to dismount, alight</def>
    </item>
    <item xml:id="aver">
        <lemma>aver</lemma>
        <source>
            <ref type="url" n="http://www.dsl.ac.uk/">Dictionary of the Scots Language</ref>
        </source>
        <partOfSpeech><i>noun</i> (1.)</partOfSpeech>
        <def>A draught-horse, a cart-horse: an old horse or one of little value</def>
    </item>
    <item xml:id="awreak">
        <lemma>awreak</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def>
            <i>trans</i>. To punish or take vengeance upon (an offence, misdeed)</def>
    </item>
    <item xml:id="bach">
        <lemma>bach</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (1) </partOfSpeech>
        <def> A stream or its valley; vale, dale, hollow; cou ~, cow pasture</def>
    </item>
    <item xml:id="bedene">
        <lemma>bedene</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adverb</i>
        </partOfSpeech>
        <def>In one body or company, together</def>
    </item>
    <item xml:id="bee">
        <lemma>bee</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (2) </partOfSpeech>
        <def>1. A ring or torque of metal, usually meant for the arm or neck; but in one case at
            least used of a finger-ring. <i>Obs</i>.</def>
    </item>
    <item xml:id="beetle">
        <lemma>beetle</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i><sup>1</sup>
        </partOfSpeech>
        <def> 1. a. An implement consisting of a heavy weight or &#8216;head,&#8217; usually of
            wood, with a handle or stock, used for driving wedges or pegs, ramming down paving
            stones, or for crushing, bruising, beating, flattening, or smoothing, in various
            industrial and domestic operations, and having various shapes according to the purpose
            for which it is used; a mall</def>
    </item>
    <item xml:id="begouth">
        <lemma>begouth</lemma>
        <source>
            <ref type="url" n="http://www.dsl.ac.uk/">Dictionary of the Scots Language</ref>
        </source>
        <partOfSpeech><i>verb</i> (1.)</partOfSpeech>
        <def><i>pa</i>.<i>t</i>. of <i>begin</i>, also used as <i>pa</i>.<i>p</i>. Gen.Sc. for Eng.
                <i>began</i></def>
    </item>
    <item xml:id="behoten">
        <lemma>behoten</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def> To promise</def>
    </item>
    <item xml:id="bemoan">
        <lemma>bemoan</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i></partOfSpeech>
        <def> 2. <i>refl</i>. To lament or bewail one&#8217;s lot</def>
    </item>
    <item xml:id="bern">
        <lemma>bern</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (1) </partOfSpeech>
        <def>2. (a) Soldier; esp., a knight; ~ of armes, man-at-arms; breneid ~, a mailed warrior;
            (b) a nobleman, a lord; &#8212; often equated with baroun baron</def>
    </item>
    <item xml:id="boist">
        <lemma>boist</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def><i>Obs</i>. 1. a. A box, a casket; chiefly used of a box for ointment, a vase or flask
            for oil, etc. (= BOX n.2 1.)</def>
    </item>
    <item xml:id="breme">
        <lemma>breme</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i> and <i>adverb</i>
        </partOfSpeech>
        <def><i>Obs</i>. exc. <i>poet</i>. and <i>dial</i>. (brim) in sense A. 6. A. adj. I.
            Celebrated, brilliant, clear, loud, distinct</def>
    </item>
    <item xml:id="betony">
        <lemma>betony</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def><i>prop</i>. A plant (<i>Stachys betonica</i>) of the Labiate order, having spiked
            purple flowers and ovate crenate leaves. In former days medicinal and magical virtues
            were attributed to it</def>
    </item>
    <item xml:id="belimp">
        <lemma>belimp</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i> (2.) </partOfSpeech>
        <def>To happen, occur, befall. Freq. with person as indirect object. (In Old English with
            dative of person). Also with <i>to</i>.</def>
    </item>
    <item xml:id="bemean">
        <lemma>bemean</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def><i>Obs</i>. 1. <i>trans</i>. To mean, signify, import; 2. <i>Obs</i>. rare.
            <i>intr</i>. To mediate, intercede</def>
    </item>
    <item xml:id="belive">
        <lemma>belive</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adverb</i> and <i>adjective</i>
        </partOfSpeech>
        <def>With speed, with haste, quickly, eagerly</def>
    </item>
    <item xml:id="beset">
        <lemma>beset</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>, 3a. </partOfSpeech>
        <def><i>fig</i>. To encompass, surround, assail, possess detrimentally: a. said of
            temptations, dangers, difficulties, obstacles, evil influences</def>
    </item>
    <item xml:id="bespit">
        <lemma>bespit</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def><i>trans</i>. To spit upon, cover or defile with spitting. Rarely <i>intr</i>. with
                <i>upon</i>. (Cf. BESPETE<i> v</i>.)</def>
    </item>
    <item xml:id="bield">
        <lemma>bield</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (3b) </partOfSpeech>
        <def>A means of help or succour</def>
    </item>
    <item xml:id="bill">
        <lemma>bill</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (1) </partOfSpeech>
        <def>A weapon of war mentioned in Old English poetry, a kind of broadsword, a falchion</def>
    </item>
    <item xml:id="bin">
        <lemma>bin / binne</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adverb</i> and <i>preposition</i>
        </partOfSpeech>
        <def> Within, inside of; in, into</def>
    </item>
    <item xml:id="bird">
        <lemma>bird</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (1c.) </partOfSpeech>
        <def><i>transf</i>. A young man, youngster, child, son</def>
    </item>
    <item xml:id="biren">
        <lemma>biren</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def>[OE ge)byrian, &amp; cp. OI byrja. In ME this verb, a synonym of biho&#333;ven, occurs
            almost exclusively in the NM and the N, and only in the 3rd person.] 1b. With personal
            subj.: (a) to be under obligation, be in duty bound (to do sth.), ought (to do)</def>
    </item>
    <item xml:id="biwilen">
        <lemma>biwilen</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i></partOfSpeech>
        <def>To trick or delude (sb.), as by witchcraft, cunning, or insincerity.</def>
    </item>
    <item xml:id="bloke">
        <lemma>bloke</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i></partOfSpeech>
        <def><i>Obs</i>. <i>intr</i>. To turn pale</def>
    </item>
    <item xml:id="bolen">
        <lemma>b&#333;len</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def>To serve (a cow) with a bull</def>
    </item>
    <item xml:id="bolning">
        <lemma>bolning</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i></partOfSpeech>
        <def>Swelling, state of being swollen; <i>concr</i>. a swelling, a tumour</def>
    </item>
    <item xml:id="bolts-head">
        <lemma>bolts-head</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (2.) </partOfSpeech>
        <def><i>Chem</i>. A globular flask with a long cylindrical neck, used in distillation</def>
    </item>
    <item xml:id="bout">
        <lemma>bout</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adverb</i> and <i>preposition</i>
        </partOfSpeech>
        <def><i>Obs</i>. or <i>dial</i>. A. <i>adv</i>.<sup>1</sup> Outside, without; out</def>
    </item>
    <item xml:id="britnen">
        <lemma>britnen</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def>3. (a) To tear or cut (sb.) to pieces; rend, slash; slay; ~ <i>to dethe</i>, ~ <i>to
                no&#541;t</i>, kill; destroy (the soul); (b) to go to pieces, be annihilated</def>
    </item>
    <item xml:id="busk">
        <lemma>busk</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (1a) </partOfSpeech>
        <def> =BUSH: A woods, grove; thicket, underbrush; bank and ~, hill and (wooded) dale; under
            the ~, in (the shelter of) the woods; (b) rank growth</def>
    </item>
    <item xml:id="busk1">
        <lemma>busk</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i> (1) </partOfSpeech>
        <def>Now rare (<i>Sc</i>., <i>Irish English</i>, and <i>Eng. regional</i> (<i>north</i>.) in
            later use). I. To prepare, and related senses. 1. a. <i>trans</i>. (<i>refl</i>.). To
            prepare or equip oneself; to make oneself ready.</def>
    </item>
    <item xml:id="buten">
        <lemma>buten</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adverb</i>and <i>preposition</i>
        </partOfSpeech>
        <def>BOUT <i>adv</i>., Outside, without; out; <i>prep</i>., Outside of, without</def>
    </item>
    <item xml:id="chalker">
        <lemma>chalker</lemma>
        <source>
            <ref type="url" n="http://www.dsl.ac.uk/">Dictionary of the Scots Language</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def> A long, white night-shirt</def>
    </item>
    <item xml:id="Clent">
        <lemma>Clent</lemma>
        <source/>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def> Clent Hills, south of Birmingham, where Kenhelm was murdered</def>
    </item>
    <item xml:id="con">
        <lemma>con</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i> (1a)</partOfSpeech>
        <def> To know. <i>Obs</i>. = CAN v.1 1 – 2 (pa. tense and pple. rarely <i>cunde</i>,
                <i>conde</i>.)</def>
    </item>
    <item xml:id="corse">
        <lemma>corse</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i></partOfSpeech>
        <def>†1. a. A living body; = CORPSE n. 1. <i>Obs</i>.</def>
    </item>
    <item xml:id="depe">
        <lemma>depe</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i></partOfSpeech>
        <def> To immerse as a religious rite, to baptize</def>
    </item>
    <item xml:id="derken">
        <lemma>derken</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i> (5, 6) </partOfSpeech>
        <def> 5 (a) Of eyes: to become blurred or blind; also fig.; (b) of a person, the mind: to
            grow confused or befuddled; 6 (a) To keep or lie still (as if in darkness or hiding);
            linger apprehensively; (b) to lie in wait, lurk</def>
    </item>
    <item xml:id="drechen">
        <lemma>drechen</lemma>
        <source>
            <ref type="url" n="http://quod.lib.umich.edu/m/med/">MED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i> (1) </partOfSpeech>
        <def> To injure (sb.), wrong, kill; damage (sth.), destroy; oppress (people, a country);
            afflict, torment, torture; ~ abrod, to scatter (an army) in defeat; (b) to disturb
            (sb.), trouble, annoy; grieve (sb.), frighten; of care, disease, love, sin, etc.:
            distress (sb.); (c) to lower (oneself), debase; (d) to delude (sb.), fool; (e) to
            speculate, ?worry about something</def>
    </item>
    <item xml:id="dree">
        <lemma>dree</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def>2. a. To endure, undergo, suffer, bear (something burdensome, grievous, or
            painful)</def>
    </item>
    <item xml:id="drublie">
        <lemma>drublie</lemma>
        <source>
            <ref type="url" n="http://www.dsl.ac.uk/">Dictionary of the Scots Language</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i>
        </partOfSpeech>
        <def> Turbid; clouded</def>
    </item>
    <item xml:id="drut">
        <lemma>drut</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def> Darling, love, friend</def>
    </item>
    <item xml:id="dule">
        <lemma>dole | dool | dule</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (2) </partOfSpeech>
        <def> Grief, sorrow, mental distress</def>
    </item>
    <item xml:id="eadi">
        <lemma>eadi</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i> (2) </partOfSpeech>
        <def> Happy, fortunate, well-omened. Also, Blessed, saintly; said of persons and their
            actions</def>
    </item>
    <item xml:id="ei">
        <lemma>ei</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i></partOfSpeech>
        <def> =EGG</def>
    </item>
    <item xml:id="ender">
        <lemma>ender</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i>
        </partOfSpeech>
        <def> Only in phrase, <i>this ender day</i>, <i>night</i>, <i>year</i>, indicating a day,
            etc. recently past</def>
    </item>
    <item xml:id="ennoy">
        <lemma>ennoy</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def> A troubled state of mind, grief, vexation; also <i>concr</i>. a cause of trouble</def>
    </item>
    <item xml:id="envire">
        <lemma>envire</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def> = ENVIRON v. 1. trans. a. To form a ring round, surround, encircle</def>
    </item>
    <item xml:id="erd">
        <lemma>erd</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def> The land where one dwells; native land, home; a region, country</def>
    </item>
    <item xml:id="eterminable">
        <lemma>eterminable</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i>
        </partOfSpeech>
        <def> That cannot be terminated; without termination or end; eternal</def>
    </item>
    <item xml:id="eath">
        <lemma>eath</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adverb</i>
        </partOfSpeech>
        <def> Easily, without difficulty</def>
    </item>
    <item xml:id="egleche">
        <lemma>egleche</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i>
        </partOfSpeech>
        <def> ? Valiant</def>
    </item>
    <item xml:id="enhaste">
        <lemma>enhaste</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def><i>Obs</i>. <i>trans</i>. To hasten, hurry; also <i>refl</i>.</def>
    </item>
    <item xml:id="erendrake">
        <lemma>erendrake</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def><i>Obs</i>. A messenger, ambassador</def>
    </item>
    <item xml:id="fallow">
        <lemma>fallow</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>adjective</i><sup>1</sup></partOfSpeech>
           <def>1. Of a pale brownish or reddish yellow colour, as withered grass or leaves.
               <i>Obs</i>. <i>exc</i>. of the coat of an animal; now chiefly in FALLOW-DEER
               <i>n</i>.</def>
    </item>
    <item xml:id="fele">
        <lemma>fele</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>adjective</i> and <i>adverb</i></partOfSpeech>
        <def> In predicative use: Much, many, numerous. Also in compar.: More in number, more
            numerous</def>
    </item>
    <item xml:id="fere">
        <lemma>fere</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>noun</i></partOfSpeech>
        <def> A companion, comrade, mate, partner; whether male or female</def>
    </item>
    <item xml:id="fere2">
        <lemma>fere</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>noun</i></partOfSpeech>
        <def> 3. An equal. a. Of a person: Peer; also in phrase, <i>without (peer or) fere</i></def>
    </item>
    <item xml:id="ferly">
        <lemma>ferly</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i> and <i>noun</i>
        </partOfSpeech>
        <def> 3a. Strange, wonderful, wondrous, marvellous</def>
    </item>
    <item xml:id="ferlies">
        <lemma>ferly</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i> 1a </partOfSpeech>
        <def>
            <i>intr</i>. To wonder</def>
    </item>
    <item xml:id="fester">
        <lemma>fester</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def> In early use = FISTULA n.; subsequently, a rankling sore, an ulcer. In mod. use:
            &#8216;A superficial suppuration resulting from irritation of the skin&#8217; (Quain
                <i>Dict. Med.</i> 1882)</def>
    </item>
    <item xml:id="fold">
        <lemma>fold</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>noun</i> 1.</partOfSpeech>
        <def>Obs. 1.a. The surface of the earth; the ground</def>
    </item>
    <item xml:id="fond">
        <lemma>fond</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>verb</i> [FAND | FOND]</partOfSpeech>
        <def>
            <i>trans</i>. To put to the proof, try, test (a person or thing); to make trial of
            (one&#8217;s strength, skill); to taste (food, etc.); in early use with
            <i>gen</i>.</def>
    </item>
    <item xml:id="found">
        <lemma>found</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>verb</i> 2</partOfSpeech>
        <def> 4.a. To set or establish (something immaterial) on a firm basis; to give a basis or
            firm support to</def>
    </item>
    <item xml:id="forcy">
        <lemma>forcy</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>adjective</i></partOfSpeech>
        <def>
            <i>Obs</i>. Chiefly <i>north</i>. Full of force, powerful, strong</def>
    </item>
    <item xml:id="fraist">
        <lemma>fraist</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>verb</i>
        </partOfSpeech>
        <def>
            <i>Obs</i>. 1. trans. To try, put to the proof, test</def>
    </item>
    <item xml:id="friar">
        <lemma>friar</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>noun</i></partOfSpeech>
        <def>†1. = BROTHER <i>n</i>., in fig. applications; esp. in Old French phrase <i>beu
                frere</i> &#8216;fair brother&#8217;. <i>Obs</i>.</def>
    </item>
    <item xml:id="frith">
        <lemma>frith</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>noun</i> (2)</partOfSpeech>
        <def> With uncertain meaning, denoting a wood of some kind, or wooded country collectively,
            esp. in poet. phrases associated with <i>fell</i>, <i>field</i></def>
    </item>
    <item xml:id="gestening">
        <lemma>gestening</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i>
        </partOfSpeech>
        <def> Entertainment as a guest, lodging, hospitality. Also, a banquet, feast.</def>
    </item>
    <item xml:id="gend">
        <lemma>gend</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>adjective</i>
        </partOfSpeech>
        <def> Foolish, simple</def>
    </item>
    <item xml:id="genitors">
        <lemma>genitor</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech>
            <i>noun</i> (1a) </partOfSpeech>
        <def> A testicle; <i>pl</i>. the testicles, but in later use = geni<i/>tals. (Cf. GENITURE
                <i>n</i>.)</def>
    </item>
    <item xml:id="gradely">
        <lemma>gradely</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>adverb</i></partOfSpeech>
        <def>2. Carefully, exactly; properly; quite, really; well</def>
    </item>
    <item xml:id="graith">
        <lemma>graith</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>
        </source>
        <partOfSpeech><i>verb</i></partOfSpeech>
        <def>
            <i>trans</i>. To make ready, prepare, put in order, repair; also, to procure</def>
    </item>
    <item xml:id="grede">
        <lemma>grede</lemma>
        <source>
            <ref type="url" n="http://www.oed.com/">OED</ref>