<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mss [ 
<!ELEMENT item (#PCDATA | loc | repos | desc | i | lang | langGrid)*>
<!ELEMENT lang (#PCDATA | i | biblio | place | langGrid | mss)*>
<!ELEMENT place (#PCDATA | country | county | town)*>
<!ATTLIST place country CDATA #IMPLIED>
<!ELEMENT langGrid (#PCDATA)>
<!ATTLIST place county CDATA #IMPLIED>
<!ATTLIST place town CDATA #IMPLIED>
<!ATTLIST item xml:id ID #IMPLIED>
<!ELEMENT biblio (#PCDATA)>
<!ATTLIST biblio key CDATA #IMPLIED>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT repos (#PCDATA | i)*>
<!ELEMENT mss (#PCDATA | item | loc | repos)*>
<!ATTLIST mss key CDATA #IMPLIED>
<!ELEMENT loc (#PCDATA)>
<!ELEMENT desc (#PCDATA | i | SUP | mss | sup | biblio)*>
]>
<mss>
    <!-- SGML: check these abbreviations I have used:
        
    <sup> and </sup>

    o-umlaut;
    slashed-o; in SkÃ¸yen
    
    NOTE: all Bodleian and Oxford College newly added from 'Changes-and-Additions files A-F

    MSS -->
    <item xml:id="Bod80G40Med">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>80.G.40.Med [now with Eng. poet. e.94]</desc>
    </item>
    <item xml:id="BodAddA11">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. A.11 (SC 28746)</desc>
    </item>
    <item xml:id="BodAddA60">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. A.60 (SC 30161)</desc>
    </item>
    <item xml:id="BodAddA106">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. A.106 (SC 29003)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 491;
                <langGrid>Grid 480 407</langGrid> (<place country="England" county="Lincolnshire"
                >Lincs</place>: Hand A); 1.144 (<place country="England" county="Leicestershire"
                >Leics</place>: Hand B, ff. 198-219v); LP 492; <langGrid>Grid 518 406</langGrid>
                (<place country="England" county="Lincolnshire">Lincs</place>: Hand C, ff.
            232v-266r); 1.144 (Lincs: Hand D, f. 266v); 1.144 (<place country="England"
                county="Lincolnshire">Lincs</place>: Hand E, ff. 267-276v, 279-285v).</lang>
        <langGrid/>
    </item>
    <item xml:id="BodAddA268">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. A.268 (SC 29387)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 498;
                <langGrid>Grid 415 370</langGrid> (<place country="England" county="Derbyshire"
                >Derbys</place>: Hand A, ff. 15-64v); LP 167; <langGrid>Grid 377 414</langGrid>
                (<place country="England" county="Lancashire">Lancs</place>: Hand B, ff. 117-136);
            LP 259; <langGrid>Grid 362 443</langGrid> (<place country="England" county="Lancashire"
                >Lancs</place>: also Hand B, ff. 139-147v).</lang>
    </item>
    <item xml:id="BodAddA369">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. A.369 (SC 29620) [<i>olim</i> Colchester]</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 6120;
                <langGrid>Grid 601 225</langGrid> (<place country="England" county="Essex"
                >Essex</place>).</lang>
    </item>
    <item xml:id="BodAddB60">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. B.60 (SC 29179)</desc>
    </item>
    <item xml:id="BodAddB66">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. B.66 (SC 29273)</desc>
    </item>
    <item xml:id="BodAddB107">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. B.107 (SC 29560)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 7620;
                <langGrid>Grid 376 272</langGrid> (<place country="England" county="Worcestershire"
                >Worcs</place>).</lang>
    </item>
    <item xml:id="BodAddC38">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. C.38 (SC 30236)</desc>
    </item>
    <item xml:id="BodAddC220">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. C.220 (SC 29430)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 6960;
                <langGrid>Grid 418 218</langGrid> (<place country="England" county="Gloucestershire"
                >Gloucs</place>).</lang>
    </item>
    <item xml:id="BodAddC280">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. C.280 (SC 29572)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 6290;
                <langGrid>Grid 553 198</langGrid> (<place country="England" county="Essex"
                >Essex</place>).</lang>
    </item>
    <item xml:id="BodAddC287">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. C.287 (SC 29640)</desc>
    </item>
    <item xml:id="BodAddE4">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. E.4 (SC 29110)</desc>
    </item>
    <item xml:id="BodAddE6">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. E.6 (SC 30314)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 6321;
                <langGrid>Grid 557 192</langGrid> (Essex); <biblio key="LAEME">LAEME</biblio> Index
            # 160; <langGrid>Grid 571 226</langGrid> (<place town="Saling">Saling</place>, N <place
                country="England" county="Essex">Essex</place>: Entry 1, Hand A, <i>The Sayings of
                St Bernard</i>); Index # 161; <langGrid>Grid 387 229</langGrid> (<place
                country="England" county="Gloucestershire">Gloucs</place> [but language may be
            somewhat mixed]: Entry 2, Hand B, <i>The XV signs before Doomsday</i>, An Exposition of
            the <i>Pater Noster</i>); Index # 162; <langGrid>Grid 577 237</langGrid> (N <place
                country="England" county="Essex">Essex</place>: Entry 3, Hand C, [last 46 lines]
            Exposition of of the <i>Pater Noster</i>).</lang>
    </item>
    <item xml:id="BodAddE7">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Addit. E.7 (SC 29284)</desc>
    </item>
    <item xml:id="BodArchDd1">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Dd.1 (SC 31502) [photographic facsimile (1893) of <mss key="BodDHumd2"/>]</desc>
    </item>
    <item xml:id="BodArchGe35">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. G.e 35</desc>
    </item>
    <item xml:id="BodArchGg39">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Gg.39 [Gough Missale 173]</desc>
    </item>
    <item xml:id="BodArcSelB8">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Selden B. 8 (SC 3338)</desc>
    </item>
    <item xml:id="BodArcSelB10">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Selden B. 10 (SC 3356)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> 1.145
            (NME).</lang>
    </item>
    <item xml:id="BodArcSelB11">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Selden B. 11 (SC 3357)</desc>
    </item>
    <item xml:id="BodArcSelB14">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Selden B. 14 (SC 3360)</desc>
        <lang><place country="England" town="London">London</place>? See <biblio key="Horobin2003"
            />, p. 160. Some of the marked forms suggest <place country="England" county="Norfolk"
                >Norfolk</place> (see <biblio key="Mosser2010"/>).</lang>
    </item>
    <item xml:id="BodArcSelB24">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Selden B. 24 (SC 3354)</desc>
    </item>
    <item xml:id="BodArcSelB26">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Selden. B. 26 (SC 3340)</desc>
    </item>
    <item xml:id="BodArcSelC813">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Arch. Selden C. 813<!-- (SC 3340)--></desc>
    </item>
    <item xml:id="BodSelSup23">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Selden Supra 23 (SC 3411)</desc>
    </item>
    <item xml:id="BodSelSup52">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Selden Supra 52 (SC 3440)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 30;
                <langGrid>Grid 417 412</langGrid> (<place country="England"
                county="Yorkshire, West Riding">WRY</place>).</lang>
    </item>
    <item xml:id="BodSelSup53">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Selden Supra 53 (SC 3441)</desc>
    </item>
    <item xml:id="BodSelSup56">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Selden Supra 56 (SC 3444)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 1.152
            (&#8216;Language of NE <place country="England" county="Lincolnshire">Lincs</place>,
            mixed with a <place country="England" county="Leicestershire">Leics</place>
            component&#8217;).</lang>
    </item>
    <item xml:id="BodSelSup73">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Selden Supra 73 (SC 3461)</desc>
    </item>
    <item xml:id="BodSelSup74">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Selden Supra 74 (SC 3462)</desc>
    </item>
    <item xml:id="BodArcSelSup90">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Selden Supra 90 (SC 3478)</desc>
    </item>
    <item xml:id="BodSelSup102">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Selden Supra 102 (SC 3490b) [Ker Pastedowns 1744, Lewis &amp; McIntosh MV84]</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> 1.152
            (&#8216;Language probably somewhat mixed, but clearly NE Midland and possibly of <place
                country="England" county="Rutland">Rutland</place>&#8217;: ff. 15-16).</lang>
    </item>
    <item xml:id="BodAsh8">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 8 (SC 8465A)</desc>
    </item>
    <item xml:id="BodAsh33">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 33 (SC 25166)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 5110;
                <langGrid>Grid 298 097</langGrid> (<place country="England" county="Devon"
                >Devon</place>).</lang>
    </item>
    <item xml:id="BodAsh34">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 34 (SC 6915)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> 1.145
                (<place country="England" county="Northern">NME</place>).</lang>
    </item>
    <item xml:id="BodAsh35">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 35 (SC 6916)</desc>
    </item>
    <item xml:id="BodAsh39">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 39 (SC 6919)</desc>
    </item>
    <item xml:id="BodAsh40">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 40 (SC 6920)</desc>
    </item>
    <item xml:id="BodAsh41">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 41 (SC 6921)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 243;
                <langGrid>Grid 392 323</langGrid> (<place country="England" county="Stafforshire"
                >Staffs</place>).</lang>
    </item>
    <item xml:id="BodAsh42">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 42 (SC 6923)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> 1.145
                (<place country="England" county="Northern">NME</place>).</lang>
    </item>
    <item xml:id="BodAsh43">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 43 (SC 6924)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 7170;
                <langGrid>Grid 378 227</langGrid> (<place country="England" county="Gloucestershire"
                >Gloucs</place>).</lang>
    </item>
    <item xml:id="BodAsh44">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 44 (SC 6925)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> 1.145
                (<place country="England" county="Durham">Durham</place>).</lang>
    </item>
    <item xml:id="BodAsh45I">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 45, Part I (SC 6926)</desc>
    </item>
    <item xml:id="BodAsh45II">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 45, Part II (SC 6927)</desc>
    </item>
    <item xml:id="BodAsh45III">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 45, Part III (SC 6928)</desc>
    </item>
    <item xml:id="BodAsh46">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 46 (SC 6930)</desc>
    </item>
    <item xml:id="BodAsh48">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 48 (SC 6933)</desc>
    </item>
    <item xml:id="BodAsh50">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 50 (SC 6935)</desc>
    </item>
    <item xml:id="BodAsh52">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 52 (SC 6936)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> 1.145
                (<place country="England" county="Lincolnshire">Lincs</place>).</lang>
    </item>
    <item xml:id="BodAsh53">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 53 (SC 6937)</desc>
    </item>
    <item xml:id="BodAsh57">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 57 (SC 6938)</desc>
    </item>
    <item xml:id="BodAsh59">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 59 (SC 6943)</desc>
    </item>
    <item xml:id="BodAsh60">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 60 (SC 6922)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 557;
                <langGrid>Grid 539 299</langGrid> (<place country="England" county="Ely"
            >Ely</place>).</lang>
    </item>
    <item xml:id="BodAsh61">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 61 (SC 6922*)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 71;
                <langGrid>Grid 478 318</langGrid> (<place country="England" county="Leicestershire"
                >Leics</place>).</lang>
    </item>
    <item xml:id="BodAsh176">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 176 (SC 6659)</desc>
    </item>
    <item xml:id="BodAsh189">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 189 (SC 6777)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 5171;
                <langGrid>Grid 343 125</langGrid> (<place country="England" county="Somerset"
                >Somerset</place>).</lang>
    </item>
    <item xml:id="BodAsh191">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 191 (SC 6667)</desc>
    </item>
    <item xml:id="BodAsh191IV">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 191, Part IV (SC 6668)</desc>
    </item>
    <item xml:id="BodAsh210">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 210 (SC 6795)</desc>
    </item>
    <item xml:id="BodAsh241">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 241</desc>
    </item>
    
    <item xml:id="BodAsh337">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 337 (SC 6683)</desc>
    </item>
    <item xml:id="BodAsh343IX">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 343, Part IX (SC 6795)</desc>
    </item>
    <item xml:id="BodAsh349I">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 349, Part I (SC 6704)</desc>
    </item>
    <item xml:id="BodAsh360I">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 360, Part I (no SC number)</desc>
    </item>
    <item xml:id="BodAsh360VII">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 360, Part VII (no SC number)</desc>
        <lang><biblio key="LAEME">LAEME</biblio> Index # 175; <langGrid>Grid 565 313</langGrid> (NW
                <place country="England" county="Norfolk">Norfolk</place>: Hand B, f. 145vb).</lang>
    </item>
    <item xml:id="BodAsh391II">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 391, Part II (SC 6873)</desc>
    </item>
    <item xml:id="BodAsh391II5">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 391, Part II.5 (SC 6733)</desc>
    </item>
    <item xml:id="BodAsh750">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 750 (SC 6621)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 5480;
                <langGrid>Grid 432 133</langGrid> (<place country="England" county="Hampshire"
                >Hants</place>: Hand A, ff. 11v-22v); LP 8491; <langGrid>Grid 591 274</langGrid>
            (Suffolk: Hand B, ff. 42-48</lang>
    </item>
    <item xml:id="BodAsh751">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 751 (SC 8193)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 200;
                <langGrid>Grid 418 396</langGrid> (<place country="England"
                county="Yorkshire, West Riding">WRY</place>).</lang>
    </item>
    <item xml:id="BodAsh754">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 754 (SC 6953)</desc>
    </item>
    <item xml:id="BodAsh759">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 759 (SC 6954)</desc>
    </item>
    <item xml:id="BodAsh781">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 781 (SC 8113)</desc>
    </item>
    <item xml:id="BodAsh970">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 970 (SC 6616)</desc>
    </item>
    <item xml:id="BodAsh1113">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1113 (SC 7391)</desc>
    </item>
    <item xml:id="BodAsh1146">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1146 (SC 8212)</desc>
    </item>
    <item xml:id="BodAsh1152">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1152 (SC 7861)</desc>
    </item>
    <item xml:id="BodAsh1280">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1280 (SC 8216)</desc>
        <lang><biblio key="LAEME">LAEME</biblio> Index # 176 (&#8216;text language not placed
            &#8212; too little to go on&#8217;).</lang>
    </item>
    <item xml:id="BodAsh1285">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1285 (SC 8221)</desc>
    </item>
    <item xml:id="BodAsh1378">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1378, Parts II, III (SC 7798)</desc>
    </item>
    <item xml:id="BodAsh1379">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1379 (SC 7683)</desc>
    </item>
    <item xml:id="BodAsh1382">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1382, Part II (SC 7577)</desc>
    </item>
    <item xml:id="BodAsh1386">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1386 (SC 8258)</desc>
    </item>
    <item xml:id="BodAsh1393">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1393 (SC 7589)</desc>
    </item>
    <item xml:id="BodAsh1394XIiii">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1394, Part XI.iii (SC 7596)</desc>
    </item>
    <item xml:id="BodAsh1397">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1397 (SC 7760)</desc>
    </item>
    <item xml:id="BodAsh1404">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1404</desc>
    </item>
    <item xml:id="BodAsh1416">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1416 (SC 7611)</desc>
    </item>
    <item xml:id="BodAsh1418">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1418 (SC 7613)</desc>
    </item>
    <item xml:id="BodAsh1438">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1438, Parts II, III (SC 7707)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> 1.145
                (<place country="England" county="Midlands">Midland</place>: Hand A, pp. 2-31);
            1.145 (<place country="England" county="Northern">NME</place>: Hand B, p. 33); 1.145
                (<place country="England" county="Nottinghamshire">Notts</place>: Hand C, pp.
            39-50); LP 908 (<place country="England" county="Lincolnshire">Lincs</place>: Hand D,
            pp. 57-71); 1.145 (<place country="Endland" county="Cambridgeshire">Cambs</place>: Hand
            E, pp. 81-92); 1.145 (<place country="England" county="Northern">NME</place>: Hand F,
            pp. 93-107); LP 398; <langGrid>Grid 455 439</langGrid> (<place country="England"
                county="Yorkshire, West Riding">WRY</place>: Hand G, p. 107-129); 1.145 (<place
                country="England" county="Midlands">Midland</place>: Hand H, pp. 131-139); 1.145
            (Southerly language: Hand J, pp. 1-52, 55-64); 1.145 (<place country="England"
                county="Midlands">Midland</place>: Hand K, pp. 53-54); LP 357 (<place
                country="England" county="Staffordshire">Staffs</place>: Hand L, ff.[<i>sic</i>?]
            67-80, 83-end).</lang>
    </item>
    <item xml:id="BodAsh1441">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1441 (SC 7624)</desc>
    </item>
    <item xml:id="BodAsh1442">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1442, Part VI (SC 7625)</desc>
    </item>
    <item xml:id="BodAsh1444">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1444, Part III (SC 7778)</desc>
    </item>
    <item xml:id="BodAsh1445">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1445 (SC 7630)</desc>
    </item>
    <item xml:id="BodAsh1448">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1448 (SC 7627)</desc>
    </item>
    <item xml:id="BodAsh1449">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1449 (SC 7554)</desc>
    </item>
    <item xml:id="BodAsh1450">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1450, Part VII (SC 7628)</desc>
    </item>
    <item xml:id="BodAsh1451">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1451 (SC 8343)</desc>
    </item>
    <item xml:id="BodAsh1464">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1464 (SC 7635)</desc>
    </item>
    <item xml:id="BodAsh1468III">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1468, Part III (SC 8177 [7004 <i>sic</i>])</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 4568;
                <langGrid>Grid 567 283</langGrid> (<place country="England" county="Suffolk"
                >Suffolk</place>).</lang>
    </item>
    <item xml:id="BodAsh1477">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1477, Parts II, III (SC 7719)</desc>
    </item>
    <item xml:id="BodAsh1478">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1478, Parts I, II (SC 7642)</desc>
    </item>
    <item xml:id="BodAsh1479">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1479 (SC 7643)</desc>
    </item>
    <item xml:id="BodAsh1480">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1480 (SC 7644)</desc>
    </item>
    <item xml:id="BodAsh1481">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1481 (SC 7722)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> LP 7680;
                <langGrid>Grid 391 260</langGrid> (<place country="England" county="Worcestershire"
                >Worcs</place>: ff. 4-12); LP 277; <langGrid>Grid 496 353</langGrid> (<place
                country="England" county="Lincolnshire">Lincs</place>: ff. 36-41v).</lang>
    </item>
    <item xml:id="BodAsh1485">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1485, Part III.ii (SC 7652)</desc>
    </item>
    <item xml:id="BodAsh1486">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1486 (SC 7004)</desc>
    </item>
    <item xml:id="BodAsh1486I">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1486, Part I (SC 7653)</desc>
    </item>
    <item xml:id="BodAsh1486III">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1486, Part III (SC 7009)</desc>
    </item>
    <item xml:id="BodAsh1487">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1487, Part II (SC 7654)</desc>
    </item>
    <item xml:id="BodAsh1490">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1490 (SC 7010)</desc>
    </item>
    <item xml:id="BodAsh1491">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1491 (SC 7656)</desc>
    </item>
    <item xml:id="BodAsh1492">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1492 (SC 7657)</desc>
    </item>
    <item xml:id="BodAsh1518">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1518</desc>
    </item>
    <item xml:id="BodAsh1524">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole 1524, Part VI (SC 8180)</desc>
    </item>
    
    <item xml:id="BodAshRol21">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole Rolls 21 (SC 7081)</desc>
    </item>
    <item xml:id="BodAshRol40">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole Rolls 40 (SC 8447)</desc>
    </item>
    <item xml:id="BodAshRol52">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Ashmole Rolls 52 (SC 7662)</desc>
    </item>
    <item xml:id="BodAuct7Q221">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Auct. 7.Q.2.21 (printed)</desc>
    </item>
    <item xml:id="BodAuctF516">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Auct. F. 5.16 (SC 2581)</desc>
    </item>
    <item xml:id="BodBar20">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Barlow 20 (SC 6420)</desc>
        <lang><biblio key="LALME">LALME</biblio> and <biblio key="eLALME">eLALME</biblio> 1.145
                (<place country="England" county="Worcestershire">Worcs</place>).</lang>
    </item>
    <item xml:id="BodBar24">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Barlow 24 (SC 6470)</desc>
    </item>
    <item xml:id="BodBar33">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Barlow 33 (SC 6488)</desc>
    </item>
    <item xml:id="Bod2C">
        <loc>Oxford</loc>
        <repos>Bodleian Library</repos>
        <desc>Bodley 2C dep. C12930</desc>